[project]
name = "analytics"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "chartengineer>=0.1.7",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "web3>=7.14.0",
    "x402>=0.2.1",
]
